'use client';

import { Line, LineChart, ResponsiveContainer, XAxis, YAxis, Tooltip, CartesianGrid } from 'recharts';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { ChartContainer, ChartTooltipContent } from '@/components/ui/chart';

const data = [
  { month: 'Jan', yield: 4.5 },
  { month: 'Feb', yield: 4.8 },
  { month: 'Mar', yield: 5.1 },
  { month: 'Apr', yield: 5.3 },
  { month: 'May', yield: 5.2 },
  { month: 'Jun', yield: 5.5 },
  { month: 'Jul', yield: 5.7 },
  { month: 'Aug', yield: 5.6 },
  { month: 'Sep', yield: 5.9 },
  { month: 'Oct', yield: 6.1 },
  { month: 'Nov', yield: 6.0 },
  { month: 'Dec', yield: 6.2 },
];

const chartConfig = {
  yield: {
    label: 'Yield',
    color: 'hsl(var(--primary))',
  },
};

export function YieldPerformance() {
  return (
    <Card className="bg-card/70 border-border/50 backdrop-blur-sm">
      <CardHeader>
        <CardTitle>Yield Performance (APY)</CardTitle>
        <CardDescription>
          Tracking the annualized yield generated by cooperative strategies.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="h-[300px] w-full">
          <ChartContainer config={chartConfig} className="h-full w-full">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={data} margin={{ top: 5, right: 10, left: -10, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border) / 0.5)" />
                <XAxis dataKey="month" stroke="hsl(var(--muted-foreground))" fontSize={12} tickLine={false} axisLine={false} />
                <YAxis stroke="hsl(var(--muted-foreground))" fontSize={12} tickLine={false} axisLine={false} tickFormatter={(value) => `${value}%`} />
                <Tooltip
                  cursor={{ stroke: 'hsl(var(--primary))', strokeWidth: 2, strokeDasharray: '3 3' }}
                  content={<ChartTooltipContent indicator="line" />}
                  wrapperStyle={{ backdropFilter: 'blur(4px)', background: 'hsl(var(--background) / 0.5)', border: '1px solid hsl(var(--border))', borderRadius: 'var(--radius)' }}
                />
                <Line
                  type="monotone"
                  dataKey="yield"
                  stroke="var(--color-yield)"
                  strokeWidth={2}
                  dot={{ r: 4, fill: 'var(--color-yield)' }}
                  activeDot={{ r: 8, style: { filter: 'drop-shadow(0 0 8px hsl(var(--primary)))' } }}
                />
              </LineChart>
            </ResponsiveContainer>
          </ChartContainer>
        </div>
      </CardContent>
    </Card>
  );
}
